### PR TITLE
update pyyaml to 6.0.1

### PR DESCRIPTION
**Pull request by orcutt989**
Fixes broken pyyaml arm64 build in our CI.

### CODE REVIEW

**Review by nicolasochem — APPROVED** [review]
thanks

**Review by harryttd — COMMENTED** [review]
i'm not sure this should be merged yet. It is a major version update of a package which seems to be a dep of another. If the code hasn't been updated we don't know what will happen.

**Comment by orcutt989** [comment]
> Please see my comment here: [#595 (comment)](https://github.com/oxheadalpha/tezos-k8s/pull/595#issuecomment-1648728333) I believe we should wait for the maintainers to fix.

Thanks @harryttd. Yes I looked at the PR and I wasn't able to understand the issue. It seems as if the arm64 build randomly stopped working for PyYAML 5.4. Could you elaborate on how the PR could be related?

**Comment by harryttd** [comment]
Yeah.. as the days go on they don't seem to want to fix this for older versions https://github.com/yaml/pyyaml/pull/731

Did you test the code to make sure it still works with the major release version?

**Comment by nicolasochem** [comment]
> Did you test the code to make sure it still works with the major release version?

We are not doing anything fancy with pyyaml so I'll assume it can still parse our yaml fine.

**Pull request merged**
