### PR TITLE
print tarball file

### PR DESCRIPTION
**Pull request by orcutt989**
```
$ TARBALL_URL=http://tezos-tarballs.s3-website.us-east-2.amazonaws.com/mainnet-rolling-tarball
$ tarball_file=$(curl -sL --head "$TARBALL_URL" | grep Location: | tail -n1 | cut -d' ' -f2)
$ echo "Downloading $tarball_file"
Downloading /tezos-mainnet-rolling-tarball-1866320.lz4
```

### CODE REVIEW

**Review by harryttd — APPROVED** [review]

**Comment by nicolasochem** [comment]
no longer needed? I think Aryeh's changes did it.

**Comment by harryttd** [comment]
The code i added logs the url that will be used to download. This pr logs the actual file name i.e.`Location` of the file.

**Comment by orcutt989** [comment]
Oops i meant to print tarball_url. IF tarball URL is already being printed then this is not needed.

**Comment by orcutt989** [comment]
> no longer needed? I think Aryeh's changes did it.

Tarball_URL wont show what block level is being downloaded.

**Pull request closed without merging**
