### PR TITLE
Empty labels dict

### PR DESCRIPTION
**Pull request by elric1**
This fixes a couple of minor issues that I found with a4c51888fb.

### CODE REVIEW

**Review by harryttd — APPROVED** [review]

**Comment by harryttd** [comment]
We discussed via slack that we will not specify any labels/selectors by default in values.yaml

**Review by nicolasochem — APPROVED** [review]
I verified that it fixes the mkchain problem, thank you.

**Comment by nicolasochem** [comment]
ha. I was about to report that activate is broken but your last push fixed it. something with rpc.

**Review by harryttd — APPROVED** [review]
Thank you!

**Comment by nicolasochem** [comment]
approved again. mkchain works without modification now

**Pull request merged**
