### PR TITLE
snapshotEngine: skip snapshot website

### PR DESCRIPTION
**Pull request by orcutt989**
This PR adds a configurable value to the snapshot engine chart `skipWebsite` that when set to `true` tells the `zip and upload` job to not build and upload the website. This is a preemptive measure for a multiple S3 vendor project that is currently underway, but I think would be useful to introduce now.

### CODE REVIEW

**Review by nicolasochem — COMMENTED** [review]
There is already a parameter to pass the jekyll page url.

It's better to skip the website build if the jekyll page is empty or unset?

Also we should probably not merge until we are done with both work streams (alternative bucket provider and faulty tarball repository). It's good to have a branch though so we can leave this open as draft.

**Comment by orcutt989** [comment]
> There is already a parameter to pass the jekyll page url.
> 
> It's better to skip the website build if the jekyll page is empty or unset?
> 
> Also we should probably not merge until we are done with both work streams (alternative bucket provider and faulty tarball repository). It's good to have a branch though so we can leave this open as draft.

Do you mean the jekyllRemoteThemeRepository or the snapshotWebsiteDomain @nicolasochem ?

**Comment by nicolasochem** [comment]
> > There is already a parameter to pass the jekyll page url.
> > It's better to skip the website build if the jekyll page is empty or unset?
> > Also we should probably not merge until we are done with both work streams (alternative bucket provider and faulty tarball repository). It's good to have a branch though so we can leave this open as draft.
> 
> Do you mean the jekyllRemoteThemeRepository or the snapshotWebsiteDomain @nicolasochem ?

Any of these 2 would work. snapshotWebsiteDomain is more logical. So if it's absent, don't deploy a website.

**Review by nicolasochem — APPROVED** [review]
thanks

**Pull request merged**
